### ISSUE TITLE
Where is the code?!

### ISSUE THREAD

**Issue by oskarko** [riggaroo/GithubUsersSearchApp#1]
Hi riggaroo,

I've been trying to see your code on this repo and there isn't code written in any class.

Where is the code?!

regards!

**Comment by MichaelObi** [comment]
@oskarko The branches contain codes that are related to each blog post in the series. Check them out

**Comment by rhonyabdullah** [comment]
I think this issue should be closed.

**Comment by meetVora1994** [comment]
@oskarko This repo is like a checkpoint repo for [2nd blog post](https://riggaroo.co.za/automated-android-testing-part-2-setup/). 
If you want full code, which is explained in [3rd blog post](https://riggaroo.co.za/introduction-android-testing-part3/), here is the [github link](https://github.com/riggaroo/GithubUsersSearchApp).
